### classifier model for predicting mental health indicators using screen and calling features

In [29]:
import pandas as pd
import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

pd.set_option('display.max_rows', None)
import matplotlib.pyplot as plt
import plotly.express as px

In [30]:
datapath = "/home/mmh/flaskDashboard/data/processedData"
screenFeaturesFilename = "ios_screen_features"
callingFeaturesFilename = "ios_calling_features"
labelsFilename = "labels"

In [31]:
screenFeatures = pd.read_csv(os.path.join(datapath, screenFeaturesFilename))
callingFeatures = pd.read_csv(os.path.join(datapath, callingFeaturesFilename))
labels = pd.read_csv(os.path.join(datapath, labelsFilename))

In [62]:
labels.dass.value_counts()

3.0    899
2.0    703
1.0    645
0.0    246
Name: dass, dtype: int64

In [32]:
# screenFeatures.info(), callingFeatures.info(), labels.info()

In [109]:
screenFeaturesAgg = screenFeatures.groupby(['participant', 'device']).mean().reset_index()
callingFeaturesAgg = callingFeatures.groupby(['participant', 'device']).mean().reset_index()

combinedFeatures = screenFeaturesAgg.merge(callingFeaturesAgg, left_on=['participant', 'device'], right_on=['participant', 'device'], how="outer")

In [92]:
data

participant device  dailysection  date_num_x  recorded_instances  \
0  PROSITC1005    ios           1.0        16.0           93.225806   
1  PROSITC1014    ios           1.0        15.0          115.965517   
2  PROSITC1016    ios           1.0         4.0           34.142857   
3  PROSITC1018    ios           1.0        15.0          115.724138   
4  PROSITC1020    ios           1.0         6.3           49.200000   

   no_of_unlocks  max_screen_on_time  max_screen_off_time  \
0      47.548387          254.322581           374.870968   
1      58.448276          197.241379           456.482759   
2      18.000000          704.571429           317.428571   
3      58.551724          309.551724           440.310345   
4      25.300000          729.900000           257.500000   

   total_screen_on_time  total_screen_off_time  ...  con  agree  extra  neuro  \
0            438.806452             997.870968  ...  5.0    8.0    5.0    9.0   
1            319.310345            1115.586207  ...  7.0    8.0    4.0    9.0   
2            970.000000             469.857143  ...  9.0    9.0    9.0    8.0   
3            614.931034             822.724138  ...  9.0    9.0    6.0    5.0   
4            910.500000             528.400000  ...  9.0    6.0    5.0    6.0   

   open   age  gender  phone  dass  current_diagnosis  
0   6.0  19.0     1.0    1.0   1.0                0.0  
1   8.0  19.0     0.0    1.0   1.0                0.0  
2   6.0  21.0     0.0    1.0   2.0                0.0  
3   9.0  25.0     0.0    1.0   3.0                0.0  
4   6.0  24.0     0.0    1.0   2.0                0.0  

[5 rows x 36 columns]

In [95]:
df = combinedFeatures
df.total_screen_on_time = df.total_screen_on_time/60
df[df.total_screen_on_time > 8]

participant device  dailysection  date_num_x  recorded_instances  \
6          DND0004    ios           1.0   28.576923           48.096154   
7          DND0005    ios           1.0   20.027027           52.000000   
11         DND1012    ios           1.0   12.304348           17.739130   
12         DND1013    ios           1.0   34.015152           35.818182   
13         DND1014    ios           1.0   19.093750           21.000000   
17         DND1022    ios           1.0   33.000000           19.815385   
20         DND1028    ios           1.0   29.500000           54.758621   
23         DND1053    ios           1.0   31.822581           22.758065   
25         DND1058    ios           1.0   21.216216           24.351351   
26         DND1062    ios           1.0   22.515152           33.454545   
27         DND1069    ios           1.0   18.606061           60.363636   
28         DND1078    ios           1.0   16.200000          105.733333   
32         DND1097    ios           1.0    8.071429           37.642857   
33         DND1104    ios           1.0   11.500000           90.363636   
36         DND1114    ios           1.0   20.933333            4.366667   
37         DND1116    ios           1.0   18.200000          115.257143   
39         DND1123    ios           1.0   16.241379           74.206897   
42         DND1135    ios           1.0   24.520833           32.000000   
45         DND1145    ios           1.0    6.400000           25.100000   
48         DND1176    ios           1.0   22.452381          128.500000   
49          GIA001    ios           1.0   12.368421           26.894737   
50          GIA002    ios           1.0   15.500000          318.300000   
52          GIA006    ios           1.0   15.172414           45.137931   
53          GIA007    ios           1.0   12.217391          161.826087   
54          GIA008    ios           1.0   10.000000           31.611111   
55          GIA010    ios           1.0   16.500000          144.031250   
56          GIA011    ios           1.0   17.757576           65.242424   
57          GIA012    ios           1.0   19.027027          183.891892   
58          GIA017    ios           1.0   26.717391           44.586957   
62          GIA022    ios           1.0   12.541667          158.041667   
63          GIA023    ios           1.0   12.500000           78.666667   
64          GIA024    ios           1.0   11.500000          218.818182   
65          GIA026    ios           1.0    8.266667           94.133333   
66          GIA027    ios           1.0   11.954545          116.227273   
68          GIA029    ios           1.0   13.500000           55.153846   
70          GIA034    ios           1.0   14.857143          174.142857   
71          GIA036    ios           1.0   10.500000           99.200000   
76          GIA043    ios           1.0   10.500000           94.444444   
78          GIA047    ios           1.0    4.000000          118.571429   
81      PROSIT0004    ios           1.0   14.500000           80.153846   
82       PROSIT001    ios           1.0   68.657658           46.198198   
83      PROSIT0011    ios           1.0   27.226415          149.018868   
84      PROSIT0013    ios           1.0   25.658537           29.926829   
85      PROSIT0015    ios           1.0    6.500000           47.500000   
86      PROSIT0019    ios           1.0   16.548387           78.806452   
89      PROSIT0024    ios           1.0   24.500000          183.708333   
91      PROSIT0026    ios           1.0   38.075758           53.893939   
92      PROSIT0027    ios           1.0   10.166667           10.833333   
93      PROSIT0031    ios           1.0   28.081633           32.775510   
96      PROSIT0041    ios           1.0   22.738095          110.642857   
97      PROSIT0044    ios           1.0   39.782609           44.014493   
98      PROSIT0046    ios           1.0   27.301887           74.264151   
99      PROSIT0047    ios       

In [110]:
screenFeaturesAgg[screenFeaturesAgg.participant.str.contains("PROSITC")].reset_index().participant.nunique(), callingFeaturesAgg[callingFeaturesAgg.participant.str.contains("PROSITC")].reset_index().participant.nunique(), combinedFeatures[combinedFeatures.participant.str.contains("PROSITC")].reset_index().participant.nunique()
# df[df['ids'].str.contains("ball")]


(595, 626, 673)

In [70]:
data = combinedFeatures.merge(labels, left_on="participant", right_on="record_id", how="inner")
data = data[~data.dass.isnull()]

featureColumns = ['no_of_unlocks', 'max_screen_on_time',
       'max_screen_off_time', 'total_screen_on_time',
       'first_screen_unlock_time', 'last_screen_lock_time',
       'no_of_missed_calls', 'no_of_rejected_calls', 'no_of_incoming_calls',
       'no_of_outgoing_calls', 'total_no_of_calls',
       'min_duration_of_single_incoming_call',
       'min_duration_of_single_outgoing_call',
       'max_duration_of_single_incoming_call',
       'max_duration_of_single_outgoing_call',
       'total_duration_of_incoming_calls', 'total_duration_of_outgoing_calls',
       'total_duration_of_all_calls']
        #, 'age', 'gender']

# labelColumns = 'current_diagnosis'
labelColumns = 'dass'

X = data.loc[:, featureColumns].fillna(0)
y = data.loc[:, labelColumns].to_list()

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    stratify=y, 
                                                    test_size=0.2)

### value counts of train_test split

In [71]:
y_counts = np.unique(y, return_counts=True)[1]
y_train_counts = np.unique(y_train, return_counts=True)[1]
y_test_counts = np.unique(y_test, return_counts=True)[1]

print(f"y       value_counts: {y_counts} \ny_train value_counts: {y_train_counts} {round(y_train_counts[0]*100/y_counts[0])}% \ny_test  value_counts: {y_test_counts} {round(y_test_counts[0]*100/y_counts[0])}%")

y       value_counts: [24 65 80 82] 
y_train value_counts: [19 52 64 65] 79% 
y_test  value_counts: [ 5 13 16 17] 21%


### training and RF model

In [72]:
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

print("[TP, FP]\n[FN, TN]")

# train prediction
y_pred_train = clf.predict(X_train)
y_train = list(map(int, y_train))
y_pred_train = list(map(int, y_pred_train))
print(f"\naccuracy_train:\n {accuracy_score(y_train, y_pred_train)}")
print(f"\nconfusion_matrix_train:\n {confusion_matrix(y_train, y_pred_train)}")

# test prediction
y_pred_test = clf.predict(X_test)
y_test = list(map(int, y_test))
y_pred_test = list(map(int, y_pred_test))
print(f"\naccuracy_test:\n {accuracy_score(y_test, y_pred_test)}")
print(f"\nconfusion_matrix_train:\n {confusion_matrix(y_test, y_pred_test)}")

[TP, FP]
[FN, TN]

accuracy_train:
 1.0

confusion_matrix_train:
 [[19  0  0  0]
 [ 0 52  0  0]
 [ 0  0 64  0]
 [ 0  0  0 65]]

accuracy_test:
 0.2549019607843137

confusion_matrix_train:
 [[0 0 3 2]
 [1 3 6 3]
 [1 2 4 9]
 [0 5 6 6]]


In [59]:
y_pred_test

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [73]:
feature_names = X_train.columns
importances = clf.feature_importances_
forest_importances = pd.DataFrame([importances], columns=feature_names)
forest_importances = forest_importances.sort_values(by=0, axis=1, ascending=True)

In [74]:
fig = px.bar(forest_importances)
fig.show()

In [55]:
df = callingFeatures.sort_values("total_duration_of_all_calls").reset_index()
fig = px.bar(df, x="participant", y="total_duration_of_all_calls")

for data in fig.data:
    data["width"] = 10
    
fig.show()

In [23]:
screenFeatures.columns

Index(['participant', 'device', 'date', 'dailysection', 'date_num',
       'recorded_instances', 'no_of_unlocks', 'max_screen_on_time',
       'max_screen_off_time', 'total_screen_on_time', 'total_screen_off_time',
       'first_screen_unlock_time', 'last_screen_lock_time'],
      dtype='object')

In [24]:
fig = px.bar(screenFeatures, x="participant", y="no_of_unlocks")

for data in fig.data:
    data["width"] = 10
    
fig.show()

In [31]:
ind = labels[labels.current_diagnosis == 1].index

In [36]:
df = screenFeatures[screenFeatures.index.isin(ind)]

In [41]:
df = df.groupby("participant").mean().reset_index()
# df.shape

In [43]:
# df = screenFeatures[screenFeatures.index in ind].groupby("participant").mean().reset_index()
fig = px.bar(df, x="participant", y="total_screen_on_time")

# for data in fig.data:
#     data["width"] = 10
    
fig.show()

In [27]:
data.columns

Index(['participant', 'device', 'date', 'dailysection', 'date_num',
       'recorded_instances', 'no_of_unlocks', 'max_screen_on_time',
       'max_screen_off_time', 'total_screen_on_time', 'total_screen_off_time',
       'first_screen_unlock_time', 'last_screen_lock_time',
       'no_of_missed_calls', 'no_of_rejected_calls', 'no_of_incoming_calls',
       'no_of_outgoing_calls', 'total_no_of_calls',
       'min_duration_of_single_incoming_call',
       'min_duration_of_single_outgoing_call',
       'max_duration_of_single_incoming_call',
       'max_duration_of_single_outgoing_call',
       'total_duration_of_incoming_calls', 'total_duration_of_outgoing_calls',
       'total_duration_of_all_calls', 'record_id', 'con', 'agree', 'extra',
       'neuro', 'open', 'age', 'gender', 'phone', 'dass', 'current_diagnosis'],
      dtype='object')